[workspace]
members = [
    "crates/yunxi-agent-core",
    "crates/yunxi-agent-protocol",
    "crates/yunxi-agent-provider",
    "crates/yunxi-agent-context",
    "crates/yunxi-agent-sandbox",
    "crates/yunxi-agent-exec",
    "crates/yunxi-agent-patch",
    "crates/yunxi-agent-tools",
    "crates/yunxi-agent-mcp",
    "crates/yunxi-agent-skills",
    "crates/yunxi-agent-multi-agent",
    "crates/yunxi-agent-storage",
    "crates/yunxi-agent-runtime",
    "crates/yunxi-agent-tui",
    "crates/yunxi-agent-cli",
]
default-members = [
    "crates/yunxi-agent-core",
    "crates/yunxi-agent-protocol",
    "crates/yunxi-agent-provider",
    "crates/yunxi-agent-context",
    "crates/yunxi-agent-sandbox",
    "crates/yunxi-agent-exec",
    "crates/yunxi-agent-patch",
    "crates/yunxi-agent-tools",
    "crates/yunxi-agent-mcp",
    "crates/yunxi-agent-skills",
    "crates/yunxi-agent-multi-agent",
    "crates/yunxi-agent-storage",
    "crates/yunxi-agent-runtime",
    "crates/yunxi-agent-tui",
    "crates/yunxi-agent-cli",
]
resolver = "2"
exclude = ["external/codex-rs", "vendor/codex-rs", "crates/yunxi-agent-codex"]

[workspace.package]
edition = "2024"
license = "Apache-2.0"
version = "1.7.4"

[workspace.dependencies]
anyhow = "1"
async-trait = "0.1"
assert_cmd = "2"
clap = { version = "4", features = ["derive"] }
predicates = "3"
futures-util = "0.3"
crossterm = "0.28"
httpdate = "1"
ratatui = "0.29"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "stream"] }
reedline = "0.36"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tempfile = "3"
thiserror = "2"
tokio = { version = "1", features = ["io-util", "macros", "process", "rt-multi-thread", "signal", "sync", "time"] }
unicode-width = "0.2"

[profile.dev]
debug = 1

[profile.test]
debug = 1
