[package]
name = "yunxi-agent-provider"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
yunxi-agent-core = { path = "../yunxi-agent-core" }

[dev-dependencies]
tokio.workspace = true
