[package]
name = "yunxi-agent-weixin"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
futures-util.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
wiremock.workspace = true
