[package]
name = "yunxi-agent-weixin"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
base64.workspace = true
chacha20poly1305.workspace = true
futures-util.workspace = true
getrandom.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
yunxi-agent-core = { path = "../yunxi-agent-core" }
yunxi-agent-storage = { path = "../yunxi-agent-storage" }

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true

[dev-dependencies]
tempfile.workspace = true
wiremock.workspace = true
yunxi-agent-provider = { path = "../yunxi-agent-provider" }
yunxi-agent-runtime = { path = "../yunxi-agent-runtime" }
yunxi-agent-tools = { path = "../yunxi-agent-tools" }
